import { runOpenAiPlaceholder } from "../utils/openai.js";

function buildFallbackSummary(profile) {
  return {
    strategicSummary:
      profile.sector === "Renewable Energy"
        ? "A policy-backed energy access opportunity exists where donor support, public-sector intent, and rural deployment requirements can be converted into a venture and capital structure."
        : `The input describes a credible ${profile.sector.toLowerCase()} opportunity with enough signal strength to justify venture and capital analysis.`,
    opportunityGap:
      profile.sector === "Renewable Energy"
        ? "The gap is not policy intent but delivery: field operations, last-mile financing, tariff design, and partner coordination remain under-structured."
        : "The gap sits between demand signal and execution capability, especially in packaging, validation, and financing.",
    policyRelevance:
      profile.sourceType.includes("government") || profile.sourceType.includes("donor")
        ? "High. The opportunity is tightly coupled to policy execution, public funding logic, or sector regulation."
        : "Moderate. The opportunity has policy adjacency but is primarily market-led.",
    riskAnalysis:
      "Primary risks include execution delay, regulatory friction, adoption uncertainty, and capital stack complexity. Human approval is required before external commitments.",
    opportunityScore: profile.sector === "Renewable Energy" ? 91 : 74,
    recommendedVentureAngle:
      profile.sector === "Renewable Energy"
        ? "Structure a deployment-ready mini-grid platform around PPP execution, donor capital, and local partner delivery."
        : "Package the opportunity into a repeatable venture thesis with validation milestones and capital fit."
  };
}

export async function analyzeIntelligence(profile, inputText) {
  const prompt = `Analyze the following opportunity and return a concise executive brief:\n\n${inputText}`;
  const openAiText = await runOpenAiPlaceholder({
    system: "You are the ThirdSpace AI OS Intelligence Engine.",
    prompt
  });

  if (openAiText) {
    return {
      strategicSummary: openAiText,
      opportunityGap: "Generated by OpenAI.",
      policyRelevance: profile.sourceType.includes("government") ? "High" : "Medium",
      riskAnalysis: "Generated by OpenAI.",
      opportunityScore: profile.sector === "Renewable Energy" ? 91 : 76,
      recommendedVentureAngle: "Generated by OpenAI."
    };
  }

  return buildFallbackSummary(profile);
}